Request review
avichazen/api-doc-example-obw pull request #12
Opened 2020-11-30 10:20 UTC by avichazen

Hi Laura - please review and approve pull request for merge

2020-12-05 18:39 UTC, lsnovich commented
Your diagram needs a small change
Where you have triangles, please make them rectangles. 

thanks!

2020-12-06 11:01 UTC, avichazen commented
@lsnovich workflow updated. please approve merge pull request

2020-12-19 18:28 UTC, lsnovich commented
I am not sure the diagram will be visable. something looks odd with the code / filename

2020-12-20 12:21 UTC, avichazen commented
@lsnovich I made the diagram in word, made a snippet from the screen, placed it in "issues", and copied that code into the readme.
Do you have a better way to suggest how to insert the workflow?

2020-12-28 07:28 UTC, lsnovich reviewed
a much better way is detailed in the [FAQ](https://docs.google.com/document/d/1E-1HT-fn1I8un6dUnrNzCA-YopOwl4DFht9VdYlMAy4/edit#)  - I just updated the FAQ with a more detailed description. 
Please take a look

2020-12-28 07:28 UTC, lsnovich commented on README.md
> +![simple workflow](https://user-images.githubusercontent.com/70967800/101278255-d912c080-37c2-11eb-8b52-c46b68bfbc19.png)
what is the name of the graphic?
it should be more like
```'![simple workflow](/folder/name.png)```

2020-12-28 18:19 UTC, avichazen commented on README.md
> +![simple workflow](https://user-images.githubusercontent.com/70967800/101278255-d912c080-37c2-11eb-8b52-c46b68bfbc19.png)
Workflow diagram fixed. Please review

2021-01-03 11:17 UTC, lsnovich commented on README.md
> +See here for [Authentication](https://github.com/avichazen/api-doc-example-obw/blob/main/Authentication.md)
```suggestion
Refer to [Authentication](https://github.com/avichazen/api-doc-example-obw/blob/main/Authentication.md), for more information. 
```

2021-01-03 11:17 UTC, lsnovich commented on README.md
> +See here for [Error Codes](https://github.com/avichazen/api-doc-example-obw/blob/main/Error%20Codes.md)
```suggestion
Refer to [Error Codes](https://github.com/avichazen/api-doc-example-obw/blob/main/Error%20Codes.md) for more information.
```

2021-01-03 11:18 UTC, lsnovich requested changes
2 small changes and then you can merge

2021-01-03 13:08 UTC, merged

2021-01-03 13:09 UTC, avichazen commented
Thanks Laura - merge applied

On Sun, 3 Jan 2021 at 13:18, lsnovich <notifications@github.com> wrote:

> *@lsnovich* requested changes on this pull request.
>
> 2 small changes and then you can merge
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/avichazen/api-doc-example-obw/pull/12#pullrequestreview-560687980>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ5OD6DJ56PU62AWK2YPH7TSYBG73ANCNFSM4UHLQMAQ>
> .
>